dist: trusty
sudo: false
language: c
os:
  - linux
addons:
  apt:
    packages:
      - shellcheck
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio ../hardware/keyboardio
## We delete the Bundle's version of Kaleidoscope, and symlink ourselves in.
## This makes sure we're using the current version of the library.
  - rm -rf ../hardware/keyboardio/avr/libraries/Kaleidoscope
  - ln -s $(pwd) ../hardware/keyboardio/avr/libraries/Kaleidoscope
  - (cd /usr/local; curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh)
  - arduino-cli core install arduino:avr
script:
#  - make travis-test KALEIDOSCOPE_TEMP_PATH=$(pwd)/.kaleidoscope-build-cache BOARD_HARDWARE_PATH=$(pwd)/../hardware
  - BOARD_HARDWARE_PATH=$(pwd)/../hardware KALEIDOSCOPE_TEMP_PATH=$(pwd)/.kaleidoscope-build-cache bin/kaleidoscope-builder compile_cli_all
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true
  directories:
    - .kaleidoscope-build-cache
    - .ccache
